<?php
/**
 * CCT Builder
 *
 * Creates CCTs and Relations programmatically via JetEngine's API
 *
 * @package PAC_Vehicle_Data_Manager
 */

// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}

/**
 * CCT Builder Class
 */
class PAC_VDM_CCT_Builder {
    
    /**
     * CCT Role definitions with required fields
     *
     * @var array
     */
    private $cct_roles = [
        'makes' => [
            'name' => 'Makes',
            'slug' => 'makes',
            'description' => 'Vehicle manufacturers/brands (top level)',
            'fields' => [
                [
                    'name' => 'make_name',
                    'title' => 'Make Name',
                    'type' => 'text',
                    'is_required' => true,
                    'description' => 'Brand name (e.g., Kia, BMW, Toyota)',
                ],
                [
                    'name' => 'make_logo',
                    'title' => 'Make Logo',
                    'type' => 'media',
                    'is_required' => false,
                    'description' => 'Brand logo image',
                ],
            ],
        ],
        'models' => [
            'name' => 'Models',
            'slug' => 'models',
            'description' => 'Vehicle models (connected to Makes)',
            'fields' => [
                [
                    'name' => 'model_name',
                    'title' => 'Model Name',
                    'type' => 'text',
                    'is_required' => true,
                    'description' => 'Model name (e.g., Stinger, M3, Camry)',
                ],
                [
                    'name' => 'make_name',
                    'title' => 'Make Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Makes CCT',
                ],
            ],
        ],
        'vehicle_configs' => [
            'name' => 'Vehicle Configs',
            'slug' => 'vehicle_configs',
            'description' => 'The Gold Record - Year + Powertrain + Generation',
            'fields' => [
                [
                    'name' => 'config_name',
                    'title' => 'Config Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'Auto-generated: "2018-2023 Kia Stinger 3.3L TT"',
                ],
                [
                    'name' => 'generation_code',
                    'title' => 'Generation Code',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'Generation identifier (e.g., CK, G80, F150)',
                ],
                [
                    'name' => 'powertrain_engine',
                    'title' => 'Powertrain/Engine',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'Engine spec (e.g., 3.3L V6 Lambda II)',
                ],
                [
                    'name' => 'year_start',
                    'title' => 'Year Start',
                    'type' => 'number',
                    'is_required' => true,
                    'description' => 'Starting model year',
                ],
                [
                    'name' => 'year_end',
                    'title' => 'Year End',
                    'type' => 'number',
                    'is_required' => true,
                    'description' => 'Ending model year',
                ],
                [
                    'name' => 'year_range_list',
                    'title' => 'Year Range List',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-GENERATED by Year Expander',
                ],
                [
                    'name' => 'make_name',
                    'title' => 'Make Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Models CCT',
                ],
                [
                    'name' => 'model_name',
                    'title' => 'Model Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Models CCT',
                ],
            ],
        ],
        'service_guides' => [
            'name' => 'Service Guides',
            'slug' => 'service_guides',
            'description' => 'Service documentation tied to Vehicle Configs',
            'fields' => [
                [
                    'name' => 'service_name',
                    'title' => 'Service Name',
                    'type' => 'text',
                    'is_required' => true,
                    'description' => 'Name of the service',
                ],
                [
                    'name' => 'service_description',
                    'title' => 'Service Description',
                    'type' => 'textarea',
                    'is_required' => false,
                    'description' => 'Detailed service description',
                ],
                [
                    'name' => 'make_name',
                    'title' => 'Make Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Vehicle Configs',
                ],
                [
                    'name' => 'model_name',
                    'title' => 'Model Name',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Vehicle Configs',
                ],
                [
                    'name' => 'generation_code',
                    'title' => 'Generation Code',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Vehicle Configs',
                ],
                [
                    'name' => 'powertrain_engine',
                    'title' => 'Powertrain/Engine',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Vehicle Configs',
                ],
                [
                    'name' => 'year_range_list',
                    'title' => 'Year Range List',
                    'type' => 'text',
                    'is_required' => false,
                    'description' => 'AUTO-SYNCED from Vehicle Configs',
                ],
            ],
        ],
    ];
    
    /**
     * Relation definitions
     *
     * @var array
     */
    private $relation_definitions = [
        'makes_to_models' => [
            'name' => 'Makes to Models',
            'parent_role' => 'makes',
            'child_role' => 'models',
            'type' => 'one_to_many',
        ],
        'models_to_configs' => [
            'name' => 'Models to Vehicle Configs',
            'parent_role' => 'models',
            'child_role' => 'vehicle_configs',
            'type' => 'one_to_many',
        ],
        'configs_to_guides' => [
            'name' => 'Vehicle Configs to Service Guides',
            'parent_role' => 'vehicle_configs',
            'child_role' => 'service_guides',
            'type' => 'one_to_many',
        ],
    ];
    
    /**
     * Get CCT role definitions
     *
     * @return array
     */
    public function get_cct_roles() {
        return $this->cct_roles;
    }
    
    /**
     * Get relation definitions
     *
     * @return array
     */
    public function get_relation_definitions() {
        return $this->relation_definitions;
    }
    
    /**
     * Create a CCT programmatically
     *
     * @param string $role_key Role key (makes, models, vehicle_configs, service_guides)
     * @param string $custom_slug Optional custom slug (defaults to role slug)
     * @param string $custom_name Optional custom name
     * @return int|WP_Error CCT ID or error
     */
    public function create_cct($role_key, $custom_slug = '', $custom_name = '') {
        if (!isset($this->cct_roles[$role_key])) {
            return new WP_Error('invalid_role', __('Invalid CCT role specified.', 'pac-vehicle-data-manager'));
        }
        
        $role = $this->cct_roles[$role_key];
        $slug = !empty($custom_slug) ? sanitize_title($custom_slug) : $role['slug'];
        $name = !empty($custom_name) ? $custom_name : $role['name'];
        
        // Check if JetEngine CCT module is available
        if (!class_exists('\\Jet_Engine\\Modules\\Custom_Content_Types\\Module')) {
            return new WP_Error('module_not_found', __('JetEngine CCT module not found.', 'pac-vehicle-data-manager'));
        }
        
        $module = \Jet_Engine\Modules\Custom_Content_Types\Module::instance();
        
        // Check if CCT already exists
        $existing = $module->manager->get_content_types($slug);
        if ($existing) {
            pac_vdm_debug_log("CCT already exists: {$slug}");
            
            // Add missing fields to existing CCT
            $this->add_missing_fields_to_cct($slug, $role['fields']);
            
            return $existing->type_id ?? 0;
        }
        
        // Build fields array for JetEngine
        $fields = $this->build_fields_array($role['fields']);
        
        // Build CCT args
        $cct_args = [
            'slug' => $slug,
            'status' => 'active',
            'args' => [
                'name' => $name,
                'slug' => $slug,
                'has_single' => false,
                'capability' => 'manage_options',
                'icon' => 'dashicons-database-view',
                'fields' => $fields,
            ],
        ];
        
        pac_vdm_debug_log("Creating CCT: {$slug}", $cct_args);
        
        // Use JetEngine's data store to create the CCT
        $data_store = $module->manager->data;
        
        if (!$data_store) {
            return new WP_Error('data_store_error', __('Could not access JetEngine data store.', 'pac-vehicle-data-manager'));
        }
        
        // Create the CCT
        $cct_id = $data_store->update_item_in_db($cct_args);
        
        if (!$cct_id) {
            return new WP_Error('create_failed', __('Failed to create CCT.', 'pac-vehicle-data-manager'));
        }
        
        // Clear JetEngine cache
        $module->manager->flush_cache();
        
        pac_vdm_debug_log("CCT created successfully", ['cct_id' => $cct_id, 'slug' => $slug]);
        
        return $cct_id;
    }
    
    /**
     * Add missing fields to an existing CCT
     *
     * FIXED: Added comprehensive error logging and validation
     *
     * @param string $cct_slug CCT slug
     * @param array  $required_fields Fields that should exist
     * @return bool Success
     */
    public function add_missing_fields_to_cct($cct_slug, $required_fields) {
        if (!class_exists('\\Jet_Engine\\Modules\\Custom_Content_Types\\Module')) {
            pac_vdm_debug_log("JetEngine CCT module not found", null, 'error');
            return false;
        }
        
        $module = \Jet_Engine\Modules\Custom_Content_Types\Module::instance();
        $content_type = $module->manager->get_content_types($cct_slug);
        
        if (!$content_type) {
            pac_vdm_debug_log("CCT not found: {$cct_slug}", null, 'error');
            return false;
        }
        
        pac_vdm_debug_log("Found CCT object", [
            'slug' => $cct_slug,
            'type_id' => $content_type->type_id ?? 'N/A',
            'class' => get_class($content_type)
        ]);
        
        // Get existing fields
        $existing_fields = $content_type->get_arg('fields') ?: [];
        $existing_field_names = array_column($existing_fields, 'name');
        
        pac_vdm_debug_log("Existing fields in CCT", [
            'count' => count($existing_fields),
            'field_names' => $existing_field_names
        ]);
        
        $fields_to_add = [];
        
        foreach ($required_fields as $field) {
            if (!in_array($field['name'], $existing_field_names)) {
                $fields_to_add[] = $field;
            }
        }
        
        if (empty($fields_to_add)) {
            pac_vdm_debug_log("No missing fields for CCT: {$cct_slug}");
            return true;
        }
        
        pac_vdm_debug_log("Fields to add to CCT: {$cct_slug}", [
            'count' => count($fields_to_add),
            'fields' => $fields_to_add
        ]);
        
        // Build new fields array
        $new_fields = $this->build_fields_array($fields_to_add);
        $all_fields = array_merge($existing_fields, $new_fields);
        
        pac_vdm_debug_log("Built JetEngine fields array", [
            'original_count' => count($existing_fields),
            'new_count' => count($new_fields),
            'total_count' => count($all_fields)
        ]);
        
        // Get the CCT data
        $data_store = $module->manager->data;
        
        if (!$data_store) {
            pac_vdm_debug_log("Data store not accessible", null, 'error');
            return false;
        }
        
        // CRITICAL FIX: Use type_id (cast to int) for database lookup
        $db_id = absint($content_type->type_id);
        
        pac_vdm_debug_log("Attempting to get CCT data for editing", [
            'type_id_raw' => $content_type->type_id,
            'db_id_int' => $db_id
        ]);
        
        $cct_data = $data_store->get_item_for_edit($db_id);
        
        if (!$cct_data) {
            pac_vdm_debug_log("Failed to get CCT data for editing", [
                'db_id' => $db_id,
                'type_id' => $content_type->type_id ?? 'N/A',
                'available_properties' => array_keys(get_object_vars($content_type))
            ], 'error');
            return false;
        }
        
        pac_vdm_debug_log("Retrieved CCT data for editing", [
            'has_args' => isset($cct_data['args']),
            'has_fields' => isset($cct_data['args']['fields']),
            'keys' => array_keys($cct_data),
            'current_fields_in_args' => isset($cct_data['args']['fields']) ? $cct_data['args']['fields'] : 'NO FIELDS KEY'
        ]);
        
        // Update fields
        $cct_data['args']['fields'] = $all_fields;
        
        pac_vdm_debug_log("About to save CCT with updated fields", [
            'cct_data_keys' => array_keys($cct_data),
            'args_keys' => array_keys($cct_data['args']),
            'fields_count' => count($cct_data['args']['fields']),
            'first_two_fields' => array_slice($cct_data['args']['fields'], 0, 2)
        ]);
        
        // Save updated CCT
        $update_result = $data_store->update_item_in_db($cct_data);
        
        pac_vdm_debug_log("update_item_in_db returned", [
            'result' => $update_result,
            'result_type' => gettype($update_result)
        ]);
        
        if (!$update_result) {
            pac_vdm_debug_log("Failed to update CCT in database", [
                'cct_slug' => $cct_slug,
                'cct_data_keys' => array_keys($cct_data)
            ], 'error');
            return false;
        }
        
        pac_vdm_debug_log("Successfully updated CCT fields", [
            'cct_slug' => $cct_slug,
            'fields_added' => count($new_fields),
            'total_fields' => count($all_fields)
        ], 'critical');
        
        // Clear cache - wrapped in try-catch because it might fail
        try {
            $module->manager->flush_cache();
            pac_vdm_debug_log("Cache flushed successfully");
        } catch (\Exception $e) {
            pac_vdm_debug_log("Cache flush failed (non-fatal)", [
                'error' => $e->getMessage()
            ], 'warning');
        }
        
        pac_vdm_debug_log("Returning true from add_missing_fields_to_cct");
        
        return true;
    }
    
    /**
     * Build JetEngine fields array format
     *
     * @param array $fields Simple field definitions
     * @return array JetEngine formatted fields
     */
    private function build_fields_array($fields) {
        $jet_fields = [];
        
        foreach ($fields as $index => $field) {
            $jet_field = [
                'name' => $field['name'],
                'title' => $field['title'],
                'type' => $this->map_field_type($field['type']),
                'object_type' => 'field',
                'is_required' => !empty($field['is_required']),
                'default_val' => '',
                'description' => $field['description'] ?? '',
            ];
            
            // Add type-specific settings
            switch ($field['type']) {
                case 'number':
                    $jet_field['min_value'] = '';
                    $jet_field['max_value'] = '';
                    $jet_field['step_value'] = '1';
                    break;
                    
                case 'media':
                    $jet_field['value_format'] = 'id';
                    break;
                    
                case 'textarea':
                    $jet_field['max_length'] = '';
                    break;
            }
            
            $jet_fields[] = $jet_field;
        }
        
        return $jet_fields;
    }
    
    /**
     * Map simple type to JetEngine type
     *
     * @param string $type Simple type
     * @return string JetEngine type
     */
    private function map_field_type($type) {
        $type_map = [
            'text' => 'text',
            'number' => 'number',
            'textarea' => 'textarea',
            'media' => 'media',
            'select' => 'select',
            'checkbox' => 'checkbox',
            'date' => 'date',
            'time' => 'time',
            'datetime' => 'datetime-local',
            'wysiwyg' => 'wysiwyg',
            'repeater' => 'repeater',
        ];
        
        return isset($type_map[$type]) ? $type_map[$type] : 'text';
    }
    
    /**
     * Create a relation between two CCTs
     *
     * @param string $parent_cct_slug Parent CCT slug
     * @param string $child_cct_slug  Child CCT slug
     * @param string $relation_name   Relation name
     * @param string $relation_type   Relation type (one_to_one, one_to_many, many_to_many)
     * @return int|WP_Error Relation ID or error
     */
    public function create_relation($parent_cct_slug, $child_cct_slug, $relation_name, $relation_type = 'one_to_many') {
        if (!function_exists('jet_engine') || !jet_engine()->relations) {
            return new WP_Error('relations_not_found', __('JetEngine Relations module not found.', 'pac-vehicle-data-manager'));
        }
        
        // Check if relation already exists
        $existing_relations = jet_engine()->relations->get_active_relations();
        
        foreach ($existing_relations as $relation_id => $relation) {
            $args = $relation->get_args();
            
            if ($args['parent_object'] === 'cct::' . $parent_cct_slug &&
                $args['child_object'] === 'cct::' . $child_cct_slug) {
                pac_vdm_debug_log("Relation already exists between {$parent_cct_slug} and {$child_cct_slug}");
                return $relation_id;
            }
        }
        
        // Build relation args
        $relation_args = [
            'name' => $relation_name,
            'parent_object' => 'cct::' . $parent_cct_slug,
            'child_object' => 'cct::' . $child_cct_slug,
            'type' => $relation_type,
            'parent_control' => true,
            'child_control' => true,
            'db_table' => true, // IMPORTANT: Store in separate DB table
            'parent_manager' => true,
            'child_manager' => true,
            'labels' => [
                'name' => $relation_name,
            ],
        ];
        
        pac_vdm_debug_log("Creating relation: {$relation_name}", $relation_args);
        
        // Get the relations data store
        $data = new \Jet_Engine\Relations\Data();
        
        // Create the relation
        $relation_id = $data->update_item_in_db([
            'slug' => sanitize_title($relation_name),
            'status' => 'active',
            'args' => $relation_args,
        ]);
        
        if (!$relation_id) {
            return new WP_Error('create_failed', __('Failed to create relation.', 'pac-vehicle-data-manager'));
        }
        
        pac_vdm_debug_log("Relation created successfully", ['relation_id' => $relation_id]);
        
        return $relation_id;
    }
    
    /**
     * Get CCT mapping status
     *
     * @return array Status for each CCT role
     */
    public function get_mapping_status() {
        $setup = get_option('pac_vdm_cct_setup', []);
        $status = [];
        
        foreach ($this->cct_roles as $role_key => $role) {
            $mapped_slug = isset($setup['ccts'][$role_key]) ? $setup['ccts'][$role_key] : '';
            $cct_exists = false;
            $fields_status = [];
            
            if (!empty($mapped_slug)) {
                // Check if CCT exists
                if (class_exists('\\Jet_Engine\\Modules\\Custom_Content_Types\\Module')) {
                    $module = \Jet_Engine\Modules\Custom_Content_Types\Module::instance();
                    $cct = $module->manager->get_content_types($mapped_slug);
                    $cct_exists = !empty($cct);
                    
                    if ($cct_exists) {
                        // FIXED: Check actual database columns, not just CCT definition
                        $existing_names = $this->get_cct_database_columns($mapped_slug);
                        
                        pac_vdm_debug_log("Checking fields for CCT: {$mapped_slug}", [
                            'role' => $role_key,
                            'columns_found' => $existing_names,
                            'required_fields' => array_column($role['fields'], 'name')
                        ]);
                        
                        foreach ($role['fields'] as $field) {
                            $fields_status[$field['name']] = [
                                'required' => !empty($field['is_required']),
                                'exists' => in_array($field['name'], $existing_names),
                                'title' => $field['title'],
                            ];
                        }
                    }
                }
            }
            
            $status[$role_key] = [
                'role_name' => $role['name'],
                'role_description' => $role['description'],
                'mapped_slug' => $mapped_slug,
                'cct_exists' => $cct_exists,
                'fields' => $fields_status,
                'is_complete' => $cct_exists && $this->check_all_fields_exist($fields_status),
            ];
        }
        
        return $status;
    }
    
    /**
     * Get relations status
     *
     * @return array Status for each relation
     */
    public function get_relations_status() {
        $setup = get_option('pac_vdm_cct_setup', []);
        $status = [];
        
        foreach ($this->relation_definitions as $key => $definition) {
            $parent_slug = isset($setup['ccts'][$definition['parent_role']]) ? $setup['ccts'][$definition['parent_role']] : '';
            $child_slug = isset($setup['ccts'][$definition['child_role']]) ? $setup['ccts'][$definition['child_role']] : '';
            
            $relation_exists = false;
            $relation_id = null;
            $has_db_table = false;
            
            if (!empty($parent_slug) && !empty($child_slug)) {
                // Check if relation exists
                if (function_exists('jet_engine') && jet_engine()->relations) {
                    $relations = jet_engine()->relations->get_active_relations();
                    
                    foreach ($relations as $rel_id => $relation) {
                        $args = $relation->get_args();
                        
                        if ($args['parent_object'] === 'cct::' . $parent_slug &&
                            $args['child_object'] === 'cct::' . $child_slug) {
                            $relation_exists = true;
                            $relation_id = $rel_id;
                            $has_db_table = !empty($args['db_table']);
                            break;
                        }
                    }
                }
            }
            
            $status[$key] = [
                'name' => $definition['name'],
                'parent_role' => $definition['parent_role'],
                'child_role' => $definition['child_role'],
                'parent_slug' => $parent_slug,
                'child_slug' => $child_slug,
                'relation_exists' => $relation_exists,
                'relation_id' => $relation_id,
                'has_db_table' => $has_db_table,
                'is_ready' => !empty($parent_slug) && !empty($child_slug),
                'is_complete' => $relation_exists && $has_db_table,
            ];
        }
        
        return $status;
    }
    
    /**
     * Get actual database columns for a CCT
     *
     * CRITICAL: For CCTs with separate DB tables, fields are COLUMNS not meta
     *
     * @param string $cct_slug CCT slug
     * @return array Array of column names
     */
    private function get_cct_database_columns($cct_slug) {
        global $wpdb;
        
        // CCT tables are named: wp_jet_cct_{slug}
        $table_name = $wpdb->prefix . 'jet_cct_' . $cct_slug;
        
        // Check if table exists
        $table_exists = $wpdb->get_var($wpdb->prepare(
            "SHOW TABLES LIKE %s",
            $table_name
        ));
        
        if (!$table_exists) {
            pac_vdm_debug_log("CCT table does not exist", ['table' => $table_name], 'warning');
            // Fallback to CCT definition
            return $this->get_cct_definition_fields($cct_slug);
        }
        
        // Get all columns from the table
        $columns = $wpdb->get_results($wpdb->prepare(
            "SHOW COLUMNS FROM `{$table_name}`"
        ), ARRAY_A);
        
        if (!$columns) {
            pac_vdm_debug_log("Could not fetch columns", ['table' => $table_name], 'warning');
            return $this->get_cct_definition_fields($cct_slug);
        }
        
        $column_names = [];
        foreach ($columns as $column) {
            $col_name = $column['Field'];
            // Exclude built-in CCT columns
            if (!in_array($col_name, ['_ID', 'cct_status', 'cct_author_id', 'cct_created', 'cct_modified', 'cct_single_post_id'])) {
                $column_names[] = $col_name;
            }
        }
        
        pac_vdm_debug_log("Fetched database columns", [
            'table' => $table_name,
            'columns' => $column_names
        ]);
        
        return $column_names;
    }
    
    /**
     * Get fields from CCT definition (fallback)
     *
     * @param string $cct_slug CCT slug
     * @return array Array of field names
     */
    private function get_cct_definition_fields($cct_slug) {
        if (!class_exists('\\Jet_Engine\\Modules\\Custom_Content_Types\\Module')) {
            return [];
        }
        
        $module = \Jet_Engine\Modules\Custom_Content_Types\Module::instance();
        $cct = $module->manager->get_content_types($cct_slug);
        
        if (!$cct) {
            return [];
        }
        
        $existing_fields = $cct->get_arg('fields') ?: [];
        return array_column($existing_fields, 'name');
    }
    
    /**
     * Check if all fields exist
     *
     * @param array $fields_status Fields status array
     * @return bool
     */
    private function check_all_fields_exist($fields_status) {
        foreach ($fields_status as $field) {
            if (!$field['exists']) {
                return false;
            }
        }
        return true;
    }
    
    /**
     * Save CCT setup configuration
     *
     * @param array $setup Setup data
     * @return bool
     */
    public function save_setup($setup) {
        $sanitized = [
            'ccts' => [],
            'relations' => [],
        ];
        
        if (isset($setup['ccts']) && is_array($setup['ccts'])) {
            foreach ($setup['ccts'] as $role => $slug) {
                $sanitized['ccts'][sanitize_key($role)] = sanitize_text_field($slug);
            }
        }
        
        if (isset($setup['relations']) && is_array($setup['relations'])) {
            foreach ($setup['relations'] as $key => $id) {
                $sanitized['relations'][sanitize_key($key)] = absint($id);
            }
        }
        
        return update_option('pac_vdm_cct_setup', $sanitized);
    }
    
    /**
     * Get current setup configuration
     *
     * @return array
     */
    public function get_setup() {
        return get_option('pac_vdm_cct_setup', [
            'ccts' => [],
            'relations' => [],
        ]);
    }
    
    /**
     * Auto-create all field mappings based on setup
     *
     * @return array Created mappings
     */
    public function auto_create_field_mappings() {
        $setup = $this->get_setup();
        $relations_status = $this->get_relations_status();
        $config_manager = new PAC_VDM_Config_Manager();
        $created_mappings = [];
        
        // Define which fields to sync at each tier
        $field_sync_rules = [
            'makes_to_models' => [
                ['source' => 'make_name', 'dest' => 'make_name'],
            ],
            'models_to_configs' => [
                ['source' => 'make_name', 'dest' => 'make_name'],
                ['source' => 'model_name', 'dest' => 'model_name'],
            ],
            'configs_to_guides' => [
                ['source' => 'make_name', 'dest' => 'make_name'],
                ['source' => 'model_name', 'dest' => 'model_name'],
                ['source' => 'generation_code', 'dest' => 'generation_code'],
                ['source' => 'powertrain_engine', 'dest' => 'powertrain_engine'],
                ['source' => 'year_range_list', 'dest' => 'year_range_list'],
            ],
        ];
        
        foreach ($relations_status as $rel_key => $rel_status) {
            if (!$rel_status['is_complete']) {
                pac_vdm_debug_log("Skipping relation (not complete)", ['rel_key' => $rel_key]);
                continue;
            }
            
            if (!isset($field_sync_rules[$rel_key])) {
                pac_vdm_debug_log("No field sync rules for relation", ['rel_key' => $rel_key]);
                continue;
            }
            
            $child_cct = $rel_status['child_slug'];
            $relation_id = $rel_status['relation_id'];
            
            pac_vdm_debug_log("Creating mappings for relation", [
                'rel_key' => $rel_key,
                'relation_id' => $relation_id,
                'child_cct' => $child_cct,
                'field_count' => count($field_sync_rules[$rel_key])
            ], 'critical');
            
            foreach ($field_sync_rules[$rel_key] as $field_rule) {
                $mapping_data = [
                    'target_cct' => $child_cct,
                    'trigger_relation' => $relation_id,
                    'source_field' => $field_rule['source'],
                    'destination_field' => $field_rule['dest'],
                    'direction' => 'both',
                    'ui_behavior' => 'readonly',
                    'enabled' => true,
                ];
                
                pac_vdm_debug_log("Attempting to save mapping", $mapping_data);
                
                $mapping_id = $config_manager->save_mapping($mapping_data);
                
                if ($mapping_id) {
                    $created_mappings[] = $mapping_data;
                    pac_vdm_debug_log("Mapping saved successfully", ['mapping_id' => $mapping_id]);
                } else {
                    pac_vdm_debug_log("Failed to save mapping", $mapping_data, 'warning');
                }
            }
        }
        
        // Auto-configure Year Expander if vehicle_configs is set
        if (!empty($setup['ccts']['vehicle_configs'])) {
            $config_manager->save_year_expander_config([
                'enabled' => true,
                'target_cct' => $setup['ccts']['vehicle_configs'],
                'start_field' => 'year_start',
                'end_field' => 'year_end',
                'output_field' => 'year_range_list',
            ]);
        }
        
        pac_vdm_debug_log('Auto-created field mappings', $created_mappings);
        
        return $created_mappings;
    }
}

